### ISSUE TITLE
Add `uffizzi connect` job to GHA workflow

### ISSUE THREAD

**Issue by gadkins** [UffizziCloud/example-voting-app#23]
When configuring Uffizzi with GitHub Actions, we need to pass container registry credentials to Uffizzi via `uffizzi connect`. While this can be done by manually running the CLI command locally, we should incorporate it into the workflow as a separate job to demonstrate the full end-to-end process for configuring GHA + Uffizzi.

**Comment by gadkins** [comment]
Note: It's not clear if `uffizzi connect` can overwrite existing credentials, or if we need to run `uffizzi disconnect` to clear any existing credentials before adding credentials with `uffizzi connect`.

**Comment by axisofentropy** [comment]
> Note: It's not clear if `uffizzi connect` can overwrite existing credentials, or if we need to run `uffizzi disconnect` to clear any existing credentials before adding credentials with `uffizzi connect`.

That's identified in this ticket https://github.com/UffizziCloud/uffizzi_cli/issues/130

**Comment by axisofentropy** [comment]
This is implemented.
